markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
pygments: true
permalink: /posts/:title
future: true
auto: false
url: http://thehackerwithin.github.com/CHAPTER
chapter: CHAPTER
name: Hacker Within
description: An initial blog and site for THW at CHAPTER
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin

